config/routes.rb
# Overrides
match '/issues/:id/quoted', :to => 'journals#new', :id => %r{(?:#{IssueID::FORMAT}-)?[0-9]+}i, :via => :post, :as => 'issue_id_quoted_issue'

app/models/moved_issue.rb
class MovedIssue < ActiveRecord::Base
    include Redmine::SafeAttributes

    belongs_to :issue

    validates_presence_of :issue, :old_key, :old_number
    validates_uniqueness_of :old_number, :scope => :old_key
    validates_length_of :old_key, :in => 1..Project::ISSUE_KEY_MAX_LENGTH
    validates_format_of :old_key, :with => %r{\A#{IssueID::FORMAT}\z}

    safe_attributes 'issue_id', 'old_key', 'old_number'
end

app/models/project_issue_key.rb
class ProjectIssueKey < ActiveRecord::Base
    include Redmine::SafeAttributes

    has_many :projects, :primary_key => :project_key, :foreign_key => :issue_key

    validates_presence_of :project_key
    validates_uniqueness_of :project_key
    validates_length_of :project_key, :in => 1..Project::ISSUE_KEY_MAX_LENGTH
    validates_format_of :project_key, :with => %r{\A#{IssueID::FORMAT}\z}, :if => Proc.new { |key| key.project_key_changed? }

    safe_attributes 'project_key'

    def reserve_issue_number!
        issue_number = 0
        self.class.transaction do
            reload(:lock => true)
            if increment!(:last_issue_number)
                issue_number = last_issue_number
            else
                raise ActiveRecord::Rollback
            end
        end
        issue_number
    end

    def self.reserve_issue_number!(key)
        issue_number = 0
        transaction do
            project_issue_key = lock(true).find_by_project_key(key)
            unless project_issue_key
                project_issue_key = new(:project_key => key)
                project_issue_key.save!
            end
            if project_issue_key.increment!(:last_issue_number)
                issue_number = project_issue_key.last_issue_number
            else
                raise ActiveRecord::Rollback
            end
        end
        issue_number
    end

end

app/views/auto_completes/issues.html.erb
<%= raw @issues.map{ |issue|
      { 'id'    => issue.issue_id,
        'label' => "#{issue.tracker} ##{issue.issue_id}: #{issue.subject.to_s.truncate(60)}",
        'value' => issue.to_param }
    }.to_json %>

app/views/issues/_id.html.erb
<% if issue.support_issue_id? %>
  <%= link_to("##{issue.id}", { :controller => 'issues', :action => 'show', :id => issue.id },
                                :id => 'legacy_issue_id',
                                :title => l(:text_legacy_issue_id),
                                :style => 'display: none;') %>
  <script type="text/javascript">
    //<![CDATA[
    var legacy_issue_id = $('#legacy_issue_id');
    if (legacy_issue_id) {
      var authors = $('div.issue p.author');
      if (authors.length > 0) {
        authors.first().before(legacy_issue_id.remove());
        legacy_issue_id.show();
      }
    }
    //]]>
  </script>
<% end %>

<% content_for(:header_tags) do %>
  <%= stylesheet_link_tag('issue', :plugin => 'issue_id') %>
<% end %>

app/views/issues/_list.html.erb
<% form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
<div class="autoscroll">
<table class="list issues">
    <thead><tr>
        <th class="checkbox hide-when-print"><%= link_to image_tag('toggle_check.png'), {}, :onclick => 'toggleIssuesSelection(Element.up(this, "form")); return false;',
                                                           :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
    <%= sort_header_tag('id', :caption => '#', :default_order => 'desc') %>
        <% query.columns.each do |column| %>
          <%= column_header(column) %>
        <% end %>
  </tr></thead>
  <% previous_group = false %>
  <tbody>
  <% issue_list(issues) do |issue, level| -%>
  <% if @query.grouped? && (group = @query.group_by_column.value(issue)) != previous_group %>
    <% reset_cycle %>
    <tr class="group open">
      <td colspan="<%= query.columns.size + 2 %>">
        <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
        <%= group.blank? ? 'None' : column_content(@query.group_by_column, issue) %> <span class="count">(<%= @issue_count_by_group[group] %>)</span>
        <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
      </td>
    </tr>
    <% previous_group = group %>
  <% end %>
  <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
    <td class="id"><%= link_to issue.to_param, :controller => 'issues', :action => 'show', :id => issue %></td>
        <% query.columns.each do |column| %><%= content_tag 'td', column_content(column, issue), :class => column.css_classes %><% end %>
  </tr>
  <% end -%>
  </tbody>
</table>
</div>
<% end -%>

app/views/issues/_title.html.erb
<% @html_title = [ "#{@issue.tracker.name} ##{@issue.to_param}: #{@issue.subject}" ] if @issue %>

app/views/issues/show.html.erb
<%= render :partial => 'action_menu' %>

<h2><%= issue_heading(@issue) %></h2>

<div class="<%= @issue.css_classes %> details">
  <% if @prev_issue_id || @next_issue_id %>
    <div class="next-prev-links contextual">
      <%= link_to_if @prev_issue_id,
                     "\xc2\xab #{l(:label_previous)}",
                     (@prev_issue_id ? issue_path(@prev_issue_id) : nil),
                     :title => "##{@prev_issue_id}",
                     :accesskey => accesskey(:previous) %> |
      <% if @issue_position && @issue_count %>
        <span class="position">
          <%= link_to_if @query_path,
                         l(:label_item_position, :position => @issue_position, :count => @issue_count),
                         @query_path %>
        </span> |
      <% end %>
      <%= link_to_if @next_issue_id,
                     "#{l(:label_next)} \xc2\xbb",
                     (@next_issue_id ? issue_path(@next_issue_id) : nil),
                     :title => "##{@next_issue_id}",
                     :accesskey => accesskey(:next) %>
    </div>
  <% end %>

  <div class="gravatar-with-child">
    <%= author_avatar(@issue.author, :size => "50") %>
    <%= assignee_avatar(@issue.assigned_to, :size => "22", :class => "gravatar-child") if @issue.assigned_to %>
  </div>

<div class="subject">
<%= render_issue_subject_with_tree(@issue) %>
</div>
        <p class="author">
        <%= authoring @issue.created_on, @issue.author %>.
        <% if @issue.created_on != @issue.updated_on %>
        <%= l(:label_updated_time, time_tag(@issue.updated_on)).html_safe %>.
        <% end %>
        </p>

<div class="attributes">
<%= issue_fields_rows do |rows|
  rows.left l(:field_status), @issue.status.name, :class => 'status'
  rows.left l(:field_priority), @issue.priority.name, :class => 'priority'

  unless @issue.disabled_core_fields.include?('assigned_to_id')
    rows.left l(:field_assigned_to), (@issue.assigned_to ? link_to_user(@issue.assigned_to) : "-"), :class => 'assigned-to'
  end
  unless @issue.disabled_core_fields.include?('category_id') || (@issue.category.nil? && @issue.project.issue_categories.none?)
    rows.left l(:field_category), (@issue.category ? @issue.category.name : "-"), :class => 'category'
  end
  unless @issue.disabled_core_fields.include?('fixed_version_id') || (@issue.fixed_version.nil? && @issue.assignable_versions.none?)
    rows.left l(:field_fixed_version), (@issue.fixed_version ? link_to_version(@issue.fixed_version) : "-"), :class => 'fixed-version'
  end

  unless @issue.disabled_core_fields.include?('start_date')
    rows.right l(:field_start_date), format_date(@issue.start_date), :class => 'start-date'
  end
  unless @issue.disabled_core_fields.include?('due_date')
    rows.right l(:field_due_date), issue_due_date_details(@issue), :class => 'due-date'
  end
  unless @issue.disabled_core_fields.include?('done_ratio')
    rows.right l(:field_done_ratio), progress_bar(@issue.done_ratio, :legend => "#{@issue.done_ratio}%"), :class => 'progress'
  end
  unless @issue.disabled_core_fields.include?('estimated_hours')
    rows.right l(:field_estimated_hours), issue_estimated_hours_details(@issue), :class => 'estimated-hours'
  end
  if User.current.allowed_to?(:view_time_entries, @project) && @issue.total_spent_hours > 0
    rows.right l(:label_spent_time), issue_spent_hours_details(@issue), :class => 'spent-time'
  end
end %>
<%= render_half_width_custom_fields_rows(@issue) %>
<%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
</div>

<% if @issue.description? %>
<hr />
<div class="description">
  <div class="contextual">
  <%= link_to l(:button_quote), issue_id_quoted_issue_path(@issue), :remote => true, :method => 'post', :class => 'icon icon-comment' if @issue.notes_addable? %>
  </div>

  <p><strong><%=l(:field_description)%></strong></p>
  <div class="wiki">
  <%= textilizable @issue, :description, :attachments => @issue.attachments %>
  </div>
</div>
<% end %>
<% if @issue.attachments.any? %>
  <hr />
  <p><strong><%=l(:label_attachment_plural)%></strong></p>
  <%= link_to_attachments @issue, :thumbnails => true %>
<% end %>

<%= render_full_width_custom_fields_rows(@issue) %>

<%= call_hook(:view_issues_show_description_bottom, :issue => @issue) %>

<% if !@issue.leaf? || User.current.allowed_to?(:manage_subtasks, @project) %>
<hr />
<div id="issue_tree">
<div class="contextual">
  <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
</div>
<p><strong><%=l(:label_subtask_plural)%></strong></p>
<%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
<%= render_descendants_tree(@issue) unless @issue.leaf? %>
<% end %>
</div>
<% end %>

<% if @relations.present? || User.current.allowed_to?(:manage_issue_relations, @project) %>
<hr />
<div id="relations">
<%= render :partial => 'relations' %>
</div>
<% end %>

</div>

<%= render partial: 'action_menu_edit' if User.current.wants_comments_in_reverse_order? %>

<div id="history">
<%= render_tabs issue_history_tabs, issue_history_default_tab %>
</div>

<%= render partial: 'action_menu_edit' unless User.current.wants_comments_in_reverse_order? %>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
  <%= f.link_to 'PDF' %>
<% end %>

<% html_title "#{@issue.tracker.name} ##{@issue.id}: #{@issue.subject}" %>

<% content_for :sidebar do %>
  <%= render :partial => 'issues/sidebar' %>

  <% if User.current.allowed_to?(:add_issue_watchers, @project) ||
    (@issue.watchers.present? && User.current.allowed_to?(:view_issue_watchers, @project)) %>
    <div id="watchers">
      <%= render :partial => 'watchers/watchers', :locals => {:watched => @issue} %>
    </div>
  <% end %>
<% end %>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, {:format => 'atom', :key => User.current.rss_key}, :title => "#{@issue.project} - #{@issue.tracker} ##{@issue.id}: #{@issue.subject}") %>
<% end %>

<%= context_menu %>

app/views/projects/_key.html.erb
<% settings = Setting.plugin_issue_id %>
<p>
  <%= form.text_field(:issue_key, :size => 10, :disabled => @project.issue_key.present? && !@project.issue_key_changed?) %>
  <% if @project.issue_key.blank? || @project.issue_key_changed? %>
    <em class="info">
      <%= l(:text_length_between, :min => 1, :max => Project::ISSUE_KEY_MAX_LENGTH) %>
      <%= l(:text_issue_key_info) %>
    </em>
    <% if @project.children.any? && settings.is_a?(Hash) && settings[:issue_key_sharing] %>
      <%= form.check_box(:share_issue_key, :no_label => true) %>
      <%= l(:text_use_issue_key_for_subprojects) %>
    <% end %>
  <% end %>
</p>
<script type="text/javascript">
  //<![CDATA[
  $('#project_identifier').closest('p').after($('#project_issue_key').closest('p').remove());
  //]]>
</script>

app/views/settings/_issue_id.html.erb
<p>
  <%= label_tag('settings[issue_key_sharing]', l(:label_issue_key_sharing)) %>
  <%= check_box_tag('settings[issue_key_sharing]', 1, @settings.is_a?(Hash) && @settings[:issue_key_sharing]) %>
  <%= l(:text_issue_key_sharing) %>
</p>